/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2023-03-31 02:45:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.HashMap;

public final class patientinfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.HashMap");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<style>\r\n");
      out.write("    .button {\r\n");
      out.write("    margin-left: 15%\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/meta.jsp", out, false);
      out.write("\r\n");
      out.write("  <title>Patient Data App</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/header.jsp", out, false);
      out.write("\r\n");
      out.write("<div class=\"main\">\r\n");
      out.write("  <h1>Patient information</h1>\r\n");
      out.write("  <form enctype=\"multipart/form-data\" method=\"POST\" action=\"/runUpload.html\">\r\n");
      out.write("         ");
 HashMap<String, String> patient = (HashMap<String, String>) request.getAttribute("patient"); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("         <p style=\"display:none\"><input type=\"text\" name=\"ID\" value=\"");
      out.print(patient.get("ID"));
      out.write("\" readonly/></p>\r\n");
      out.write("         <input type=\"file\" name=\"profile\"/>\r\n");
      out.write("         <input type=\"submit\" value=\"Upload Profile Picture\"/>\r\n");
      out.write("  </form>\r\n");
      out.write("  <form method=\"POST\" action=\"/patientinfo.html\">\r\n");
      out.write("        <p style=\"display:none\"><input type=\"text\" name=\"id\" value=\"");
      out.print(patient.get("ID"));
      out.write("\" readonly/></p>\r\n");
      out.write("        <input type=\"submit\" value=\"Delete Profile Picture\" class=\"button\"/>\r\n");
      out.write("  </form>\r\n");
      out.write("  <form method=\"POST\" action=\"/runUpdate.html\">\r\n");
      out.write("      <ul>\r\n");
      out.write("        ");

            String profile = patient.get("PROFILE");
        
      out.write("\r\n");
      out.write("        <img src=\"");
      out.print("./images/"+profile);
      out.write("\" alt=\"profile picture\">\r\n");
      out.write("        <p style=\"display:none\"><input type=\"text\" name=\"PROFILE\" value=\"");
      out.print(patient.get("PROFILE"));
      out.write("\" readonly></p>\r\n");
      out.write("\r\n");
      out.write("        <li><label>ID: </label><input type=\"text\" name=\"ID\" size=\"40\" value=\"");
      out.print(patient.get("ID"));
      out.write("\" readonly></li>\r\n");
      out.write("        <li><label>Birth Date: </label><input type=\"text\" name=\"BIRTHDATE\" size=\"40\" value=\"");
      out.print(patient.get("BIRTHDATE"));
      out.write("\"></li>\r\n");
      out.write("        <li><label>Death Date: </label><input type=\"text\" name=\"DEATHDATE\" size=\"40\" value=\"");
      out.print(patient.get("DEATHDATE"));
      out.write("\"></li>\r\n");
      out.write("        <li><label>SSN: </label><input type=\"text\" name=\"SSN\" size=\"40\" value=\"");
      out.print(patient.get("SSN"));
      out.write("\"></li>\r\n");
      out.write("        <li><label>Drivers: </label><input type=\"text\" name=\"DRIVERS\" size=\"40\" value=\"");
      out.print(patient.get("DRIVERS"));
      out.write("\"></li>\r\n");
      out.write("        <li><label>Passport: </label><input type=\"text\" name=\"PASSPORT\" size=\"40\" value=\"");
      out.print(patient.get("PASSPORT"));
      out.write("\"></li>\r\n");
      out.write("        <li><label>Prefix: </label><input type=\"text\" name=\"PREFIX\" size=\"40\" value=\"");
      out.print(patient.get("PREFIX"));
      out.write("\"></li>\r\n");
      out.write("        <li><label>First Name: </label><input type=\"text\" name=\"FIRST\" size=\"40\" value=\"");
      out.print(patient.get("FIRST"));
      out.write("\"></li>\r\n");
      out.write("        <li><label>Last Name: </label><input type=\"text\" name=\"LAST\" size=\"40\" value=\"");
      out.print(patient.get("LAST"));
      out.write("\"></li>\r\n");
      out.write("        <li><label>Suffix: </label><input type=\"text\" name=\"SUFFIX\" size=\"40\" value=\"");
      out.print(patient.get("SUFFIX"));
      out.write("\"></li>\r\n");
      out.write("        <li><label>Maiden: </label><input type=\"text\" name=\"MAIDEN\" size=\"40\" value=\"");
      out.print(patient.get("MAIDEN"));
      out.write("\"></li>\r\n");
      out.write("        <li><label>Marital: </label><input type=\"text\" name=\"MARITAL\" size=\"40\" value=\"");
      out.print(patient.get("MARITAL"));
      out.write("\"></li>\r\n");
      out.write("        <li><label>Race: </label><input type=\"text\" name=\"RACE\" size=\"40\" value=\"");
      out.print(patient.get("RACE"));
      out.write("\"></li>\r\n");
      out.write("        <li><label>Ethnicity: </label><input type=\"text\" name=\"ETHNICITY\" size=\"40\" value=\"");
      out.print(patient.get("ETHNICITY"));
      out.write("\"></li>\r\n");
      out.write("        <li><label>Gender: </label><input type=\"text\" name=\"GENDER\" size=\"50\" value=\"");
      out.print(patient.get("GENDER"));
      out.write("\"></li>\r\n");
      out.write("        <li><label>Birth Place: </label><input type=\"text\" name=\"BIRTHPLACE\" size=\"40\" value=\"");
      out.print(patient.get("BIRTHPLACE"));
      out.write("\"></li>\r\n");
      out.write("        <li><label>Address: </label><input type=\"text\" name=\"ADDRESS\" size=\"40\" value=\"");
      out.print(patient.get("ADDRESS"));
      out.write("\"></li>\r\n");
      out.write("        <li><label>City: </label><input type=\"text\" name=\"CITY\" size=\"40\" value=\"");
      out.print(patient.get("CITY"));
      out.write("\"></li>\r\n");
      out.write("        <li><label>State: </label><input type=\"text\" name=\"STATE\" size=\"40\" value=\"");
      out.print(patient.get("STATE"));
      out.write("\"></li>\r\n");
      out.write("        <li><label>ZIP: </label><input type=\"text\" name=\"ZIP\" size=\"40\" value=\"");
      out.print(patient.get("ZIP"));
      out.write("\"></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("      <input type=\"submit\" value=\"Save Changes\" class=\"button\" />\r\n");
      out.write("  </form>\r\n");
      out.write("  <form method=\"POST\" action=\"/runDelete.html\">\r\n");
      out.write("    <p style=\"display:none\"><input type=\"text\" name=\"ID\" value=\"");
      out.print(patient.get("ID"));
      out.write("\" readonly/></p>\r\n");
      out.write("    <input type=\"submit\" value=\"Delete Record\" class=\"button\" />\r\n");
      out.write("  </form>\r\n");
      out.write("</div>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
